packages:
  - "app-mech"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: false
  esbuild: true
  prisma: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
