// Generated by Schema Studio
// Provider: mysql
// Project: Analytics Engine – 1.0112

import { boolean, decimal, index, int, json, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const user = mysqlTable("user", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Client-side generated ID for pre-auth tracking
  trackingId: varchar("tracking_id", { length: 36 }),
  // Authenticated user email (null for anonymous)
  email: varchar("email", { length: 255 }).unique(),
  // Display name set after authentication
  name: varchar("name", { length: 255 }),
  // ISO 3166-1 alpha-2 country code from IP geolocation
  country: varchar("country", { length: 2 }),
  // Whether the user has been linked to a known identity
  isIdentified: boolean("is_identified").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("user_email_unique").on(table.email),
]);

export const session = mysqlTable("session", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // User this session belongs to
  userId: text("user_id").notNull().references(() => user.id),
  // Device class: desktop | mobile | tablet
  device: varchar("device", { length: 20 }),
  // Browser name and major version
  browser: varchar("browser", { length: 50 }),
  // Operating system name and version
  os: varchar("os", { length: 50 }),
  // Client IP address (IPv4 or IPv6)
  clientIp: varchar("client_ip", { length: 45 }),
  // Total events recorded in this session
  eventCount: int("event_count").notNull().default(0),
  // Session start timestamp
  startedAt: timestamp("started_at").notNull(),
  // Session end timestamp (null while active)
  endedAt: timestamp("ended_at"),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
}, (table) => [
  index("session_userId_index").on(table.userId),
]);

export const event = mysqlTable("event", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Session this event was captured in
  sessionId: text("session_id").notNull().references(() => session.id),
  // User who triggered the event
  userId: text("user_id").notNull(),
  // Event name slug, e.g. page_view or button_click
  name: varchar("name", { length: 100 }).notNull(),
  // Broad event category for grouping in reports
  category: varchar("category", { length: 50 }),
  // Arbitrary key-value data attached to the event at capture time
  payload: text("payload"),
  // Exact client-side timestamp when the event fired
  occurredAt: timestamp("occurred_at").notNull(),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
}, (table) => [
  index("event_sessionId_index").on(table.sessionId),
]);

export const event_attribute = mysqlTable("event_attribute", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Parent event UUID
  eventId: text("event_id").notNull(),
  // Attribute name, e.g. page_url or product_id
  key: varchar("key", { length: 100 }).notNull(),
  // String-serialised attribute value
  value: varchar("value", { length: 500 }).notNull(),
  // Value data type hint: string | number | boolean | json
  valueType: varchar("value_type", { length: 20 }).notNull(),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
});

export const funnel = mysqlTable("funnel", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Human-readable funnel name
  name: varchar("name", { length: 150 }).notNull(),
  // What this funnel measures and why it matters
  description: text("description"),
  // Whether this funnel is currently being tracked
  isActive: boolean("is_active").notNull().default(true),
  // Maximum days allowed between consecutive steps
  windowDays: int("window_days").notNull().default(30),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
});

export const conversion_step = mysqlTable("conversion_step", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Owning funnel UUID
  funnelId: text("funnel_id").notNull().references(() => funnel.id),
  // Step label shown in reports
  name: varchar("name", { length: 150 }).notNull(),
  // Event name that satisfies this step
  eventName: varchar("event_name", { length: 100 }).notNull(),
  // Zero-based position within the funnel
  stepOrder: int("step_order").notNull().default(0),
  // Percentage of users reaching this step from the previous one
  conversionRate: decimal("conversion_rate"),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("conversion_step_funnelId_stepOrder_unique").on(table.funnelId, table.stepOrder),
]);

export const data_source = mysqlTable("data_source", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Display name for the data source
  name: varchar("name", { length: 150 }).notNull(),
  // Integration type: sdk | webhook | csv | api
  type: varchar("type", { length: 50 }).notNull(),
  // Encrypted connection configuration (API keys, endpoints, options)
  settings: json("settings"),
  // Whether ingestion from this source is currently enabled
  isActive: boolean("is_active").notNull().default(true),
  // Timestamp of the most recent successful data pull
  lastSyncedAt: timestamp("last_synced_at"),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
});

export const dashboard = mysqlTable("dashboard", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // User who owns this dashboard
  userId: text("user_id").notNull().references(() => user.id),
  // Dashboard display name
  name: varchar("name", { length: 150 }).notNull(),
  // Short description of what this dashboard tracks
  description: varchar("description", { length: 500 }),
  // Grid layout preset: grid | single | wide
  layout: varchar("layout", { length: 20 }).notNull(),
  // Whether the dashboard is accessible via a public share link
  isPublic: boolean("is_public").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
});

export const widget = mysqlTable("widget", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // Parent dashboard UUID
  dashboardId: text("dashboard_id").notNull().references(() => dashboard.id),
  // Visualisation type: line_chart | bar_chart | funnel | number | table
  type: varchar("type", { length: 50 }).notNull(),
  // Widget heading shown to viewers
  title: varchar("title", { length: 150 }).notNull(),
  // Query definition, axis settings, filters, and colour overrides
  config: json("config"),
  // Position within the dashboard grid (row-major order)
  sortOrder: int("sort_order").notNull().default(0),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
}, (table) => [
  index("widget_dashboardId_index").on(table.dashboardId),
]);

export const report = mysqlTable("report", {
  // Primary key — Prisma client-generated UUID
  id: text("id").notNull(),
  // User who created or owns the report
  userId: text("user_id").notNull().references(() => user.id),
  // Report display name
  name: varchar("name", { length: 150 }).notNull(),
  // Raw SQL or DSL query used to produce the report
  query: text("query").notNull(),
  // Output format, grouping, date range, and filter settings
  config: json("config"),
  // Execution status: pending | running | completed | failed
  status: varchar("status", { length: 20 }).notNull(),
  // Next scheduled run time (null for on-demand reports)
  scheduledAt: timestamp("scheduled_at"),
  // Record creation timestamp
  createdAt: timestamp("created_at").notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at").notNull() /* @updatedAt */,
});
