// Generated by Schema Studio
// Provider: postgresql
// Project: Content Hub Pro – 1.0112

import { bigint, boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

export const author = pgTable("author", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Author full display name
  name: varchar("name", { length: 150 }).notNull(),
  // Unique login and contact email
  email: varchar("email", { length: 255 }).notNull(),
  // Short editorial biography shown on author pages
  biography: text("biography"),
  // URL to the author profile image
  avatarUrl: varchar("avatar_url", { length: 500 }),
  // Whether the author can publish new content
  isActive: boolean("is_active").notNull().default(true),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});

export const post = pgTable("post", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Author who owns and is primarily responsible for this post
  authorId: uuid("author_id").notNull().references(() => author.id),
  // Article headline shown in listings and the browser tab
  title: varchar("title", { length: 255 }).notNull(),
  // URL-safe unique identifier used in the post permalink
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  // Full article content — supports markdown or rich-text HTML
  content: text("content").notNull(),
  // Publication lifecycle: draft | review | published | archived
  status: varchar("status", { length: 20 }).notNull(),
  // Timestamp when the post was or will be publicly visible
  publishedAt: timestamp("published_at", { withTimezone: true }),
  // SEO fields, open-graph image, custom schema, and reading time
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("post_slug_unique").on(table.slug),
  index("post_authorId_index").on(table.authorId),
]);

export const draft = pgTable("draft", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Post this revision belongs to
  postId: uuid("post_id").notNull().references(() => post.id),
  // Author who saved this revision
  authorId: uuid("author_id").notNull(),
  // Full body snapshot at the time of saving
  content: text("content").notNull(),
  // Monotonically increasing revision number within the post
  version: text("version").notNull().default(1),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const category = pgTable("category", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Parent category UUID for sub-categories (null = top-level)
  parentId: uuid("parent_id").references(() => category.id),
  // Category label shown in navigation and listings
  name: varchar("name", { length: 100 }).notNull(),
  // URL-safe unique identifier
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  // Short description of editorial scope for this category
  description: text("description"),
  // Display order among siblings
  sortOrder: integer("sort_order").notNull().default(0),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("category_slug_unique").on(table.slug),
]);

export const tag = pgTable("tag", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Tag display label
  name: varchar("name", { length: 80 }).notNull(),
  // URL-safe unique identifier
  slug: varchar("slug", { length: 80 }).notNull().unique(),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [
  uniqueIndex("tag_slug_unique").on(table.slug),
]);

export const media = pgTable("media", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Author who uploaded the file
  authorId: uuid("author_id").notNull().references(() => author.id),
  // Asset category: image | video | document | audio
  type: varchar("type", { length: 20 }).notNull(),
  // Public CDN or storage URL to the file
  url: varchar("url", { length: 500 }).notNull(),
  // IANA media type, e.g. image/jpeg or application/pdf
  mimeType: varchar("mime_type", { length: 100 }).notNull(),
  // File size in bytes
  fileSize: bigint("file_size", { mode: "number" }).notNull(),
  // Accessibility alt text for images
  altText: varchar("alt_text", { length: 255 }),
  // Image dimensions, duration, codec, EXIF data
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});

export const comment = pgTable("comment", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Post this comment is attached to
  postId: uuid("post_id").notNull().references(() => post.id),
  // Registered author who submitted the comment (null for guests)
  authorId: uuid("author_id"),
  // Display name for non-authenticated commenters
  guestName: varchar("guest_name", { length: 100 }),
  // Comment content submitted by the reader
  body: text("body").notNull(),
  // Whether the comment has passed moderation and is publicly visible
  isApproved: boolean("is_approved").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  index("comment_postId_index").on(table.postId),
]);

export const page = pgTable("page", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Author responsible for maintaining this page
  authorId: uuid("author_id").notNull().references(() => author.id),
  // Page heading shown in the browser tab and h1
  title: varchar("title", { length: 255 }).notNull(),
  // URL-safe unique path segment, e.g. about or contact
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  // Full page body content in markdown or HTML
  body: text("body").notNull(),
  // Publication state: draft | published | hidden
  status: varchar("status", { length: 20 }).notNull(),
  // Whether this page appears in the main navigation menu
  showInNav: boolean("show_in_nav").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("page_slug_unique").on(table.slug),
]);

export const menu = pgTable("menu", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Internal name used to identify this menu in the CMS
  name: varchar("name", { length: 100 }).notNull(),
  // Theme slot: header | footer | sidebar | mobile
  location: varchar("location", { length: 50 }).notNull(),
  // Whether this menu is currently rendered by the theme
  isActive: boolean("is_active").notNull().default(true),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});

export const nav_item = pgTable("nav_item", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Owning menu UUID
  menuId: uuid("menu_id").notNull().references(() => menu.id),
  // Parent menu item UUID for nested dropdowns (null = top-level)
  parentId: uuid("parent_id"),
  // Link text displayed in the navigation
  title: varchar("title", { length: 100 }).notNull(),
  // Destination URL — absolute or site-relative path
  url: varchar("url", { length: 500 }).notNull(),
  // Whether the link opens in a new browser tab
  openInNewTab: boolean("open_in_new_tab").notNull().default(false),
  // Display order among siblings at the same nesting level
  sortOrder: integer("sort_order").notNull().default(0),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});
