// Generated by Schema Studio
// Provider: postgresql
// Project: Shopfront Manager – 1.0112

import { boolean, doublePrecision, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

export const product = pgTable("product", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Display name shown in the storefront
  name: varchar("name", { length: 255 }).notNull(),
  // URL-safe unique identifier for the product page
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  // Long-form product description (supports markdown)
  description: text("description"),
  // Selling price in the store base currency
  price: doublePrecision("price").notNull(),
  // Units currently available in inventory
  stockQuantity: integer("stock_quantity").notNull().default(0),
  // Whether the product is visible and purchasable
  isActive: boolean("is_active").notNull().default(true),
  // Arbitrary additional attributes (dimensions, colour, tags)
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("product_slug_unique").on(table.slug),
]);

export const category = pgTable("category", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Category label shown to shoppers
  name: varchar("name", { length: 100 }).notNull(),
  // URL-safe unique identifier
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  // Optional editorial description of the category
  description: text("description"),
  // Parent category UUID for nested hierarchies (null = root)
  parentId: uuid("parent_id"),
  // Display order among sibling categories
  sortOrder: integer("sort_order").notNull().default(0),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("category_slug_unique").on(table.slug),
]);

export const customer = pgTable("customer", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Unique login email address
  email: varchar("email", { length: 255 }).notNull().unique(),
  // Given name
  firstName: varchar("first_name", { length: 100 }).notNull(),
  // Family name
  lastName: varchar("last_name", { length: 100 }).notNull(),
  // Contact phone number in E.164 format
  phone: varchar("phone", { length: 20 }),
  // Whether the email address has been confirmed
  emailVerified: boolean("email_verified").notNull().default(false),
  // Arbitrary extra attributes (referral source, preferences)
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  uniqueIndex("customer_email_unique").on(table.email),
]);

export const address = pgTable("address", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Owning customer UUID
  customerId: uuid("customer_id").notNull().references(() => customer.id),
  // Address purpose: shipping or billing
  type: varchar("type", { length: 20 }).notNull(),
  // Street line including house number
  street: varchar("street", { length: 255 }).notNull(),
  // City or locality name
  city: varchar("city", { length: 100 }).notNull(),
  // State, province, or region (optional)
  state: varchar("state", { length: 100 }),
  // ZIP or postal code
  postalCode: varchar("postal_code", { length: 20 }).notNull(),
  // ISO 3166-1 alpha-2 country code
  country: text("country").notNull(),
  // Whether this is the customer's default shipping address
  isDefault: boolean("is_default").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
});

export const basket = pgTable("basket", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Owning customer UUID (null for guest carts)
  customerId: uuid("customer_id").references(() => customer.id),
  // Cart lifecycle state: active | abandoned | converted
  status: varchar("status", { length: 20 }).notNull(),
  // Running sum of all cart item prices
  total: doublePrecision("total").notNull(),
  // Timestamp after which the cart is considered abandoned
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});

export const basket_item = pgTable("basket_item", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Owning cart UUID
  cartId: uuid("cart_id").notNull().references(() => basket.id),
  // Referenced product UUID
  productId: uuid("product_id").notNull(),
  // Number of units added to the cart
  quantity: integer("quantity").notNull().default(1),
  // Product price captured at the time of adding to cart
  price: numeric("price").notNull(),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});

export const order = pgTable("order", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Customer who placed the order
  customerId: uuid("customer_id").notNull().references(() => customer.id),
  // Delivery address UUID
  shippingAddressId: uuid("shipping_address_id").notNull().references(() => address.id),
  // Order lifecycle status: pending | confirmed | shipped | delivered | cancelled
  status: varchar("status", { length: 30 }).notNull(),
  // Sum of order items before tax and shipping
  subtotal: numeric("subtotal").notNull(),
  // Shipping fee applied at checkout
  shippingCost: numeric("shipping_cost").notNull(),
  // Final charged amount including all fees
  totalAmount: numeric("total_amount").notNull(),
  // Carrier tracking info, discount codes, and other contextual data
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  index("order_customerId_index").on(table.customerId),
]);

export const order_item = pgTable("order_item", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Owning order UUID
  orderId: uuid("order_id").notNull().references(() => order.id),
  // Referenced product UUID at time of purchase
  productId: uuid("product_id").notNull().references(() => product.id),
  // Product name captured at purchase time (immutable snapshot)
  productName: varchar("product_name", { length: 255 }).notNull(),
  // Units purchased
  quantity: integer("quantity").notNull().default(1),
  // Price per unit at time of purchase
  unitPrice: numeric("unit_price").notNull(),
  // quantity × unitPrice
  totalPrice: numeric("total_price").notNull(),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [
  index("order_item_orderId_index").on(table.orderId),
]);

export const payment = pgTable("payment", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Order this payment applies to
  orderId: uuid("order_id").notNull().references(() => order.id),
  // Payment gateway identifier: stripe | paypal | braintree
  provider: varchar("provider", { length: 50 }).notNull(),
  // Amount charged in the order currency
  amount: numeric("amount").notNull(),
  // ISO 4217 three-letter currency code
  currency: varchar("currency", { length: 3 }).notNull(),
  // Outcome: pending | succeeded | failed | refunded
  status: varchar("status", { length: 30 }).notNull(),
  // External transaction ID returned by the payment provider
  providerRef: varchar("provider_ref", { length: 100 }),
  // Raw provider response payload for auditing
  metadata: jsonb("metadata"),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
}, (table) => [
  index("payment_orderId_index").on(table.orderId),
]);

export const review = pgTable("review", {
  // Primary key — database-generated UUID
  id: uuid("id").notNull(),
  // Reviewed product UUID
  productId: uuid("product_id").notNull().references(() => product.id),
  // Reviewing customer UUID
  customerId: uuid("customer_id").notNull(),
  // Star rating from 1 (worst) to 5 (best)
  rating: doublePrecision("rating").notNull(),
  // Free-text review content
  body: text("body"),
  // Whether the review has passed moderation
  isApproved: boolean("is_approved").notNull().default(false),
  // Record creation timestamp
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  // Record last-modified timestamp
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() /* @updatedAt */,
});
